### PR TITLE
Update to v0.18.0

### PR DESCRIPTION
**Pull request by sebp**
Updates the package to v0.18.0 and adjusts dependencies accordingly.

### CODE REVIEW

**Comment by sebp** [comment]
Builds for Python 3.7 fail, because scikit-learn 1.1 requires Python 3.8+, see https://scikit-learn.org/stable/whats_new/v1.1.html#minimal-dependencies

**Comment by sebp** [comment]
@janjagusch @xhochy would you mind having a look at the PR?

**Review by janjagusch — APPROVED** [review]
Thank you for your help!

**Review by janjagusch — CHANGES_REQUESTED** [review]
@sebp, thanks for your help. could you skip builds for Python version <3.8, please?

More details [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#skipping-builds).

**Comment by sebp** [comment]
@janjagusch Done, but I'm not sure what the CircleCI failure is about.

**Comment by janjagusch** [comment]
> @janjagusch Done, but I'm not sure what the CircleCI failure is about.

The CirlceCI run is new to me. @xhochy, do you know what's going on here?

**Comment by sebp** [comment]
> > @janjagusch Done, but I'm not sure what the CircleCI failure is about.
> 
> The CirlceCI run is new to me. @xhochy, do you know what's going on here?

The issue seems similar to https://github.com/conda-forge/admin-requests/pull/493
I think you need to remove the CircleCI webhook from the settings of this repository.

**Review by xhochy — APPROVED** [review]

**Comment by xhochy** [comment]
> > @janjagusch Done, but I'm not sure what the CircleCI failure is about.
> 
> The CirlceCI run is new to me. @xhochy, do you know what's going on here?

All fine, Circle isn't used anymore.

**Pull request merged**
